version: "3.9"
services:
  api:
    container_name: api
    build:
      dockerfile: deployment/Docker/Dockerfile
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ".:/go/src/github.com/valentin-iordanov/v-uni-project"
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
